interface map {
  [key: string]: Array<string>;
}

export const groupList = ["blackpink", "gidle", "itzy", "ive", "newjeans"];

export const albumnMap: map = {
  blackpink: [
    "square one",
    "square two",
    "as if its your last",
    "so hot",
    "re:black pink",
    "square up",
    "ddu du ddu du",
    "blackpink in your area",
    "blackpink arena tour 2018",
    "kill this love",
    "blackpink 2018 tour [in your area] seoul",
    "kill this love (japanese version)",
    "awesome",
    "blackpink 2019-2020 world tour in your area",
    "how you like that",
    "ice cream",
    "the album",
    "blackpink 2021 the show live",
    "the album (japanese version)",
    "ready for love",
    "pink venom",
    "born pink",
  ],
  gidle: [
    "latata",
    "oh my god",
    "i made",
    "heat",
    "i trust",
    "i burn",
    "i am",
    "i love",
    "i feel",
    "dumdi dumdi",
    "i never die",
  ],
  itzy: [
    "itz different",
    "itz icy",
    "itz me",
    "not shy",
    "trust me",
    "guess who",
    "in the morning",
    "break ice",
    "joyful moment",
    "whatz itzy",
    "crazy in love",
    "itz itzy",
    "voltage",
    "checkmate",
    "blah blah blah",
    "cheshire",
    "kill my doubt",
    "ringo",
  ],
  ive: [
    "eleven",
    "love dive",
    "after like",
    "kitsch",
    "ive ive",
    "wave",
    "ive pepsi",
  ],
  newjeans: ["new jeans", "ditto", "omg", "tell me", "zero", "get up"],
};

export const memberMap: map = {
  blackpink: ["jisoo", "jennie", "rose", "lisa"],
  gidle: ["miyeon", "minnie", "soyeon", "yuqi", "shuhua"],
  itzy: ["yeji", "lia", "ryujin", "chaeryeong", "yuna"],
  ive: ["gaeul", "yujin", "rei", "wonyoung", "liz", "leeseo"],
  newjeans: ["minji", "hanni", "danielle", "haerin", "hyein"],
};
